[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
gl = "0.14.0"
glutin = "0.28.0"
egui = "0.19.0"
egui-winit = "0.19.0"